import re

with open('crates/nes-desktop/src/rta.rs', 'r') as f:
    content = f.read()

replacements = {
    "pub enum ProfileStatus {": "/// Indicates whether a profile is draft or published.\npub enum ProfileStatus {",
    "    Draft,": "    /// The profile is a draft and is ignored by strict auto-selection.\n    Draft,",
    "    #[default]\n    Published,": "    #[default]\n    /// The profile is active and can be used for valid competitive runs.\n    Published,",
    "pub enum TimerClock {": "/// Determines how time is measured during a run.\npub enum TimerClock {",
    "    #[default]\n    Wall,": "    #[default]\n    /// Time is measured using the system's absolute wall clock.\n    Wall,",
    "pub enum FocusLossPolicy {": "/// Policy for handling host OS window focus loss during an active run.\npub enum FocusLossPolicy {",
    "    AutoPause,": "    /// The emulator pauses automatically when focus is lost.\n    AutoPause,",
    "    Invalidate,": "    /// The run is immediately marked invalid if focus is lost.\n    Invalidate,",
    "    #[default]\n    Continue,": "    #[default]\n    /// The run continues normally in the background.\n    Continue,",
    "pub enum ForbiddenAction {": "/// An action that disqualifies a competitive speedrun attempt.\npub enum ForbiddenAction {",
    "    #[default]\n    Rewind,": "    #[default]\n    /// The user triggered the rewind feature.\n    Rewind,",
    "    SaveLoad,": "    /// The user loaded a manual save state.\n    SaveLoad,",
    "    FrameStep,": "    /// The user advanced the emulator one frame at a time.\n    FrameStep,",
    "pub enum TriggerWidth {": "/// The width of memory read for trigger evaluation.\npub enum TriggerWidth {",
    "    #[default]\n    U8,": "    #[default]\n    /// 8-bit memory read.\n    U8,",
    "    U16,": "    /// 16-bit memory read.\n    U16,",
    "    U32,": "    /// 32-bit memory read.\n    U32,",
    "pub enum TriggerOp {": "/// Operator used to compare the memory value against the target value.\npub enum TriggerOp {",
    "    #[default]\n    Eq,": "    #[default]\n    /// Trigger when memory equals the target.\n    Eq,",
    "    Ne,": "    /// Trigger when memory does not equal the target.\n    Ne,",
    "    Gt,": "    /// Trigger when memory is strictly greater than the target.\n    Gt,",
    "    Gte,": "    /// Trigger when memory is greater than or equal to the target.\n    Gte,",
    "    Lt,": "    /// Trigger when memory is strictly less than the target.\n    Lt,",
    "    Lte,": "    /// Trigger when memory is less than or equal to the target.\n    Lte,",
    "    BitSet,": "    /// Trigger when a specific bitmask is set in memory.\n    BitSet,",
    "    BitClear,": "    /// Trigger when a specific bitmask is clear in memory.\n    BitClear,",
    "    Changed,": "    /// Trigger when the memory value changes from its previous state.\n    Changed,",
    "pub struct TimerPolicy {": "/// Configures the behavior of the speedrun timer.\npub struct TimerPolicy {",
    "    pub clock: TimerClock,": "    /// The active clock mode.\n    pub clock: TimerClock,",
    "    pub focus_loss: FocusLossPolicy,": "    /// Handling behavior for OS window focus loss.\n    pub focus_loss: FocusLossPolicy,",
    "    pub manual_fallback: bool,": "    /// Whether manual timer control is permitted.\n    pub manual_fallback: bool,",
    "pub struct InvalidationPolicy {": "/// Configures which actions instantly invalidate the run.\npub struct InvalidationPolicy {",
    "    pub invalidate_on: Vec<ForbiddenAction>,": "    /// List of actions that invalidate the run.\n    pub invalidate_on: Vec<ForbiddenAction>,",
    "pub struct SplitPolicy {": "/// Configures how intermediate segment splits are handled.\npub struct SplitPolicy {",
    "    pub append_only: bool,": "    /// Whether splits can only be added sequentially.\n    pub append_only: bool,",
    "    pub manual_hotkey: String,": "    /// Key binding for manually triggering a split.\n    pub manual_hotkey: String,",
    "pub struct LoggingPolicy {": "/// Configures artifact logging for a run.\npub struct LoggingPolicy {",
    "    pub save_input_log: bool,": "    /// Whether to record full frame-by-frame controller inputs.\n    pub save_input_log: bool,",
    "pub struct TriggerRule {": "/// A memory condition that must be met to trigger an event.\npub struct TriggerRule {",
    "    pub address: u16,": "    /// The starting memory address to evaluate.\n    pub address: u16,",
    "    pub width: TriggerWidth,": "    /// How many bytes to read starting from the address.\n    pub width: TriggerWidth,",
    "    pub op: TriggerOp,": "    /// The comparison operator.\n    pub op: TriggerOp,",
    "    pub value: u32,": "    /// The target value to compare against.\n    pub value: u32,",
    "    pub debounce_frames: u32,": "    /// Minimum frame duration the condition must hold true.\n    pub debounce_frames: u32,",
    "    pub require_consecutive: u32,": "    /// Number of consecutive frames the condition must hold true.\n    pub require_consecutive: u32,",
    "pub struct LoadedProfile {": "/// An RTA Profile loaded into memory along with its path.\npub struct LoadedProfile {",
    "    pub path: PathBuf,": "    /// Path to the loaded profile TOML file.\n    pub path: PathBuf,",
    "    pub profile: RtaProfile,": "    /// The parsed profile data.\n    pub profile: RtaProfile,",
    "pub enum ProfileSelectionSource {": "/// How the active profile was selected.\npub enum ProfileSelectionSource {",
    "    AutoByRomHash,": "    /// Profile was matched automatically based on the ROM hash.\n    AutoByRomHash,",
    "    ManualOverride,": "    /// Profile was explicitly overridden by the user.\n    ManualOverride,",
    "pub struct ProfileSelection {": "/// The result of attempting to match a profile to a ROM.\npub struct ProfileSelection {",
    "    pub selected: LoadedProfile,": "    /// The chosen profile.\n    pub selected: LoadedProfile,",
    "    pub source: ProfileSelectionSource,": "    /// How the profile was chosen.\n    pub source: ProfileSelectionSource,",
    "pub enum RtaSessionState {": "/// The current operational state of the RTA manager.\npub enum RtaSessionState {",
    "    Idle,": "    /// Waiting for the start trigger condition to be met.\n    Idle,",
    "    Armed,": "    /// The start trigger has been primed but not yet fully met.\n    Armed,",
    "    Running,": "    /// The speedrun is active and time is being recorded.\n    Running,",
    "    Finished,": "    /// The end trigger was hit and the run concluded successfully.\n    Finished,",
    "    InvalidPractice,": "    /// The run was invalidated by a forbidden action.\n    InvalidPractice,",
    "pub enum SplitSource {": "/// Identifies how a split event was triggered.\npub enum SplitSource {",
    "    Automatic,": "    /// The split was triggered by a memory condition.\n    Automatic,",
    "    Manual,": "    /// The split was triggered manually by user input.\n    Manual,",
    "pub struct SplitEvent {": "/// Represents a completed segment in the run.\npub struct SplitEvent {",
    "    pub name: String,": "    /// The name of the completed segment.\n    pub name: String,",
    "    pub source: SplitSource,": "    /// How the split was triggered.\n    pub source: SplitSource,",
    "    pub frame: u64,": "    /// The absolute frame counter when the split occurred.\n    pub frame: u64,",
    "    pub elapsed_ms: u128,": "    /// Wall clock elapsed time in milliseconds.\n    pub elapsed_ms: u128,",
    "pub struct InputLogFrame {": "/// Stores the state of both controllers for a single frame.\npub struct InputLogFrame {",
    "    pub frame: u64,": "    /// The frame number this input belongs to.\n    pub frame: u64,",
    "    pub controller1_bits: u8,": "    /// Bitmask for controller 1 buttons.\n    pub controller1_bits: u8,",
    "    pub controller2_bits: u8,": "    /// Bitmask for controller 2 buttons.\n    pub controller2_bits: u8,",
    "    pub elapsed_ms: u128,": "    /// Wall clock time recorded for this frame.\n    pub elapsed_ms: u128,",
    "pub enum RtaEvent {": "/// Events emitted by the RTA manager describing state changes.\npub enum RtaEvent {",
    "    Started,": "    /// The run has officially started.\n    Started,",
    "    Paused,": "    /// The run timer is paused.\n    Paused,",
    "    Resumed,": "    /// The run timer has resumed.\n    Resumed,",
    "    Split(SplitEvent),": "    /// A split segment was completed.\n    Split(SplitEvent),",
    "    Invalidated(String),": "    /// The run was marked invalid.\n    Invalidated(String),",
    "    Finished(Duration),": "    /// The run was successfully completed.\n    Finished(Duration),",
    "pub struct RunArtifactPaths {": "/// Holds the output paths for generated run artifacts.\npub struct RunArtifactPaths {",
    "    pub run_json_path: PathBuf,": "    /// The path to the saved summary JSON report.\n    pub run_json_path: PathBuf,",
    "    pub input_log_path: Option<PathBuf>,": "    /// The path to the frame-by-frame input log, if enabled.\n    pub input_log_path: Option<PathBuf>,",
    "pub struct DraftOutput {": "/// Output paths for the results of a calibration session.\npub struct DraftOutput {",
    "    pub profile_path: PathBuf,": "    /// The generated TOML draft profile.\n    pub profile_path: PathBuf,",
    "    pub report_path: PathBuf,": "    /// The comprehensive JSON calibration report.\n    pub report_path: PathBuf,",
    "pub struct CalibrationRecorder {": "/// Analyzes emulator memory snapshots to auto-generate trigger rules.\npub struct CalibrationRecorder {",
    "pub const DEFAULT_RTA_PROFILES_DIR: &str = \"config/rta/profiles\";": "/// Default directory path for RTA profile TOML definitions.\npub const DEFAULT_RTA_PROFILES_DIR: &str = \"config/rta/profiles\";",
    "pub const DEFAULT_RTA_RUNS_DIR: &str = \"runs/rta\";": "/// Default directory path for saving completed RTA run artifacts.\npub const DEFAULT_RTA_RUNS_DIR: &str = \"runs/rta\";",
    "pub struct RtaRuntimeConfig {": "/// Runtime configuration settings passed to the RTA manager.\npub struct RtaRuntimeConfig {",
    "    pub profile_id_override: Option<String>,": "    /// Forces the use of a specific profile ID regardless of ROM hash.\n    pub profile_id_override: Option<String>,",
    "    pub profiles_dir: PathBuf,": "    /// Path to read profiles from.\n    pub profiles_dir: PathBuf,",
    "    pub runs_dir: PathBuf,": "    /// Path to write artifacts to.\n    pub runs_dir: PathBuf,",
    "    pub calibrate: bool,": "    /// Enables calibration recording mode.\n    pub calibrate: bool,",
    "pub mod serde_iter {": "/// Internal helper module for safely serializing iterators in Serde.\npub mod serde_iter {"
}

for pat, repl in replacements.items():
    if content.count(pat) == 1:
        content = content.replace(pat, repl)
    else:
        # If multiple instances exist, only replace the first to avoid mutating tests
        parts = content.split(pat, 1)
        content = parts[0] + repl + parts[1]

with open('crates/nes-desktop/src/rta.rs', 'w') as f:
    f.write(content)
