//! Experimental visualizer that renders NES audio samples into a waveform image.

#[cfg(feature = "nova")]
use crate::bmp::encode_bmp;

/// A utility for converting raw PCM audio samples into a visual oscilloscope waveform.
///
/// `AudioOscilloscope` takes a buffer of 16-bit audio samples (like those generated by the APU)
/// and renders them into a graphical representation (BMP). It automatically decimates
/// the sample buffer to fit the requested image width, ensuring the full waveform envelope
/// is visible even for long audio clips.
#[cfg(feature = "nova")]
pub struct AudioOscilloscope;

#[cfg(feature = "nova")]
impl AudioOscilloscope {
    /// Renders a slice of audio samples into a waveform BMP image.
    ///
    /// The waveform is drawn in neon green against a solid black background.
    /// It scales the 16-bit samples (`-32768` to `32767`) to fit within the provided `height`.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use nes_core::experimental::audio_oscilloscope::AudioOscilloscope;
    ///
    /// let samples = vec![0, 10000, 30000, -10000, -30000];
    /// let bmp_bytes = AudioOscilloscope::render_waveform(&samples, 100, 50).unwrap();
    /// assert_eq!(&bmp_bytes[0..2], b"BM");
    /// ```
    pub fn render_waveform(
        samples: &[i16],
        width: usize,
        height: usize,
    ) -> Result<Vec<u8>, String> {
        if width == 0 || height == 0 {
            return Err("Width and height must be greater than zero".to_string());
        }

        let mut rgba = vec![0u8; width * height * 4];

        // Draw a dark green center line (silence)
        let center_y = height / 2;
        if center_y < height {
            for x in 0..width {
                let idx = (center_y * width + x) * 4;
                rgba[idx] = 0;
                rgba[idx + 1] = 64; // dark green
                rgba[idx + 2] = 0;
                rgba[idx + 3] = 255;
            }
        }

        if samples.is_empty() {
            return encode_bmp(width, height, &rgba);
        }

        let samples_per_pixel = samples.len() as f32 / width as f32;

        for x in 0..width {
            let start_idx = (x as f32 * samples_per_pixel) as usize;
            let end_idx = ((x + 1) as f32 * samples_per_pixel) as usize;

            // Ensure we read at least one sample, and don't go out of bounds
            let end_idx = end_idx.min(samples.len()).max(start_idx + 1);
            let start_idx = start_idx.min(samples.len().saturating_sub(1));

            let mut min_val = i16::MAX;
            let mut max_val = i16::MIN;

            for &sample in &samples[start_idx..end_idx] {
                min_val = min_val.min(sample);
                max_val = max_val.max(sample);
            }

            let min_y = Self::sample_to_y(min_val, height);
            let max_y = Self::sample_to_y(max_val, height);

            let top = min_y.min(max_y);
            let bottom = min_y.max(max_y);

            for y in top..=bottom {
                if y < height {
                    let idx = (y * width + x) * 4;
                    rgba[idx] = 0;
                    rgba[idx + 1] = 255; // neon green
                    rgba[idx + 2] = 0;
                    rgba[idx + 3] = 255;
                }
            }
        }

        encode_bmp(width, height, &rgba)
    }

    fn sample_to_y(sample: i16, height: usize) -> usize {
        let normalized = (sample as f32 - i16::MIN as f32) / (i16::MAX as f32 - i16::MIN as f32);
        // Invert Y so positive values go UP
        let y = height as f32 - (normalized * height as f32);
        (y as usize).clamp(0, height.saturating_sub(1))
    }
}

#[cfg(all(test, feature = "nova"))]
mod tests {
    use super::*;

    #[test]
    fn render_empty_waveform() {
        let bmp = AudioOscilloscope::render_waveform(&[], 100, 50).unwrap();
        assert_eq!(&bmp[0..2], b"BM");
    }

    #[test]
    fn render_sine_waveform() {
        let mut samples = Vec::new();
        for i in 0..44100 {
            let val = ((i as f32 * 0.1).sin() * 20000.0) as i16;
            samples.push(val);
        }
        let bmp = AudioOscilloscope::render_waveform(&samples, 800, 200).unwrap();
        assert_eq!(&bmp[0..2], b"BM");
    }

    #[test]
    fn invalid_dimensions() {
        let res = AudioOscilloscope::render_waveform(&[0, 100], 0, 50);
        assert!(res.is_err());
    }
}
