//! Experimental Audio Oscilloscope Visualizer.
//!
//! This module overlays the current APU audio waveform directly onto the
//! PPU framebuffer. It's a fun mashup of the audio and video domains,
//! allowing players to "see" the sound waves generated by the game.

#![cfg(feature = "nova")]

use crate::constants::{FRAME_HEIGHT, FRAME_WIDTH};

// The maximum amplitude we expect from the APU, roughly corresponding to
// the MAX_SAMPLE_AMPLITUDE in `apu.rs`.
const VISUAL_MAX_AMPLITUDE: f32 = 12_000.0;

/// An experimental visualizer that draws an audio waveform on a framebuffer.
pub struct AudioOscilloscope;

impl AudioOscilloscope {
    /// Overlays the given audio `samples` onto the RGBA `framebuffer`.
    ///
    /// The waveform is drawn as a green line. The amplitude of each sample
    /// dictates its vertical Y-position on the screen, while its index in the
    /// sample buffer dictates its horizontal X-position.
    ///
    /// `framebuffer` must be `FRAME_WIDTH * FRAME_HEIGHT * 4` bytes.
    /// `samples` can be any length, but will be mapped to the width of the screen.
    pub fn apply_to_framebuffer(framebuffer: &mut [u8], samples: &[i16]) {
        if samples.is_empty() {
            return;
        }

        let expected_fb_len = FRAME_WIDTH * FRAME_HEIGHT * 4;
        if framebuffer.len() != expected_fb_len {
            return; // Invalid framebuffer
        }

        // We want to map the length of `samples` to `FRAME_WIDTH`.
        // If we have more samples than width, we'll step through them.
        let step = (samples.len() as f32) / (FRAME_WIDTH as f32);

        // Center the wave vertically on the screen.
        let center_y = (FRAME_HEIGHT / 2) as i32;

        // Max vertical variance from the center (e.g. half the screen height, minus a little padding)
        let max_y_offset = (FRAME_HEIGHT / 2) as f32 - 10.0;

        for x in 0..FRAME_WIDTH {
            let sample_idx = ((x as f32) * step) as usize;
            // Clamp index just in case of floating point weirdness
            let sample = samples[sample_idx.min(samples.len() - 1)];

            // Normalize sample from [-12000, 12000] to [-1.0, 1.0]
            let normalized = (sample as f32) / VISUAL_MAX_AMPLITUDE;

            // Clamp normalized value between -1.0 and 1.0 to stay on screen
            let clamped = normalized.clamp(-1.0, 1.0);

            // Calculate Y position (invert so positive is up)
            let y_offset = -(clamped * max_y_offset);
            let y = center_y + (y_offset as i32);

            let safe_y = y.clamp(0, (FRAME_HEIGHT - 1) as i32) as usize;

            let pixel_idx = (safe_y * FRAME_WIDTH + x) * 4;

            // Draw a bright green pixel for the waveform over whatever was there
            framebuffer[pixel_idx] = 0; // R
            framebuffer[pixel_idx + 1] = 255; // G
            framebuffer[pixel_idx + 2] = 0; // B
            framebuffer[pixel_idx + 3] = 255; // A
        }
    }
}

#[cfg(all(test, feature = "nova"))]
mod tests {
    use super::*;

    #[test]
    fn oscilloscope_draws_flat_line_for_zero_amplitude() {
        let mut framebuffer = vec![0u8; FRAME_WIDTH * FRAME_HEIGHT * 4];
        // Flat silence
        let samples = vec![0i16; 735]; // Typical frame sample count

        AudioOscilloscope::apply_to_framebuffer(&mut framebuffer, &samples);

        let center_y = FRAME_HEIGHT / 2;

        // Every X pixel along the center Y row should be green
        for x in 0..FRAME_WIDTH {
            let pixel_idx = (center_y * FRAME_WIDTH + x) * 4;
            assert_eq!(framebuffer[pixel_idx], 0); // R
            assert_eq!(framebuffer[pixel_idx + 1], 255); // G
            assert_eq!(framebuffer[pixel_idx + 2], 0); // B
            assert_eq!(framebuffer[pixel_idx + 3], 255); // A
        }
    }

    #[test]
    fn oscilloscope_handles_empty_samples() {
        let mut framebuffer = vec![0u8; FRAME_WIDTH * FRAME_HEIGHT * 4];
        let original_fb = framebuffer.clone();

        let samples: Vec<i16> = Vec::new();
        AudioOscilloscope::apply_to_framebuffer(&mut framebuffer, &samples);

        // Framebuffer should remain untouched
        assert_eq!(framebuffer, original_fb);
    }

    #[test]
    fn oscilloscope_handles_invalid_framebuffer_size() {
        let mut framebuffer = vec![0u8; 10]; // Too small
        let original_fb = framebuffer.clone();

        let samples = vec![0i16; 100];
        AudioOscilloscope::apply_to_framebuffer(&mut framebuffer, &samples);

        // Should abort early and not panic
        assert_eq!(framebuffer, original_fb);
    }
}
