//! Experimental audio oscilloscope visualizer.
//!
//! This module provides a way to visualize the APU's audio output as a waveform
//! directly on the framebuffer, useful for debugging sound or creating aesthetic overlays.

#[cfg(feature = "nova")]
use crate::constants::{FRAME_HEIGHT, FRAME_WIDTH};

/// An experimental visualizer that draws an audio waveform on the screen.
///
/// `AudioOscilloscope` takes an audio sample buffer and renders it as an oscilloscope-style
/// line overlay on the provided RGBA framebuffer. This allows players or developers to "see"
/// the sound being produced by the APU in real-time.
#[cfg(feature = "nova")]
pub struct AudioOscilloscope;

#[cfg(feature = "nova")]
impl AudioOscilloscope {
    /// Draws the audio waveform directly on an RGBA framebuffer.
    ///
    /// The `frame` must be a valid RGBA framebuffer slice of length `FRAME_WIDTH * FRAME_HEIGHT * 4`.
    /// The `samples` is a slice of 16-bit PCM audio samples generated by the emulator for the current frame.
    ///
    /// The waveform is drawn near the bottom of the screen.
    pub fn draw_waveform(frame: &mut [u8], samples: &[i16], color: [u8; 4]) {
        if samples.is_empty() {
            return;
        }

        // Height of the waveform drawing area
        let height = 64;
        // Position it near the bottom of the screen (e.g., above the bottom 16 pixels)
        let center_y = FRAME_HEIGHT.saturating_sub(height / 2).saturating_sub(16);

        // Calculate a crude rolling average for a smoother line,
        // but for simplicity we'll just sample the buffer directly.
        for x in 0..FRAME_WIDTH {
            // Map the x coordinate (0..256) to a sample index (0..samples.len())
            let sample_idx = (x * samples.len()) / FRAME_WIDTH;
            let sample = samples[sample_idx];

            // Map the 16-bit PCM sample (-32768..32767) to a pixel offset (-32..+31)
            // Divide by 512 as an arbitrary scale to fit normal volume levels into the height.
            let scaled = (sample / 512) as isize;

            // Clamp the offset to the waveform area height
            let y_offset = scaled.clamp(-(height as isize / 2), (height as isize / 2) - 1);

            // Calculate the actual Y coordinate on the screen
            let y = (center_y as isize - y_offset) as usize;

            Self::draw_pixel(frame, x, y, color);

            // Draw a vertical line to connect the previous point if we wanted,
            // but for a simple oscilloscope, dots or simple lines are fine.
            // To make it look more continuous, let's just leave it as dots for now.
        }
    }

    /// Draws a single pixel onto the RGBA framebuffer.
    fn draw_pixel(frame: &mut [u8], x: usize, y: usize, color: [u8; 4]) {
        if x >= FRAME_WIDTH || y >= FRAME_HEIGHT {
            return;
        }
        let base_idx = (y * FRAME_WIDTH + x) * 4;
        if base_idx + 3 < frame.len() {
            frame[base_idx] = color[0]; // R
            frame[base_idx + 1] = color[1]; // G
            frame[base_idx + 2] = color[2]; // B
            frame[base_idx + 3] = color[3]; // A
        }
    }
}

#[cfg(all(test, feature = "nova"))]
mod tests {
    use super::*;
    use crate::constants::FRAME_RGBA_BYTES;

    #[test]
    fn test_draw_waveform_modifies_framebuffer() {
        let mut frame = vec![0_u8; FRAME_RGBA_BYTES];

        // Generate a simple test waveform
        let mut samples = vec![0_i16; 735]; // ~1 frame of audio at 44.1kHz
        samples[0] = 32767; // Max positive
        samples[100] = -32768; // Max negative

        // Pick a coordinate in the middle of the screen width
        let test_x = 128;
        let sample_idx = (test_x * samples.len()) / FRAME_WIDTH;
        // Make the sample at test_x clearly positive
        samples[sample_idx] = 10000;

        let color = [255, 0, 255, 255]; // Magenta
        AudioOscilloscope::draw_waveform(&mut frame, &samples, color);

        // The expected Y coordinate should be calculated.
        let height = 64;
        let center_y = FRAME_HEIGHT - (height / 2) - 16;
        let scaled = (10000 / 512) as isize;
        let y_offset = scaled.clamp(-(height as isize / 2), (height as isize / 2) - 1);
        let expected_y = (center_y as isize - y_offset) as usize;

        let base_idx = (expected_y * FRAME_WIDTH + test_x) * 4;

        assert_eq!(frame[base_idx], 255);
        assert_eq!(frame[base_idx + 1], 0);
        assert_eq!(frame[base_idx + 2], 255);
        assert_eq!(frame[base_idx + 3], 255);
    }
}
