//! Experimental motion detection using frame differencing.
//!
//! This module compares consecutive video frames generated by the PPU
//! to highlight areas of the screen that are changing. This can be used
//! to separate moving objects (sprites, scrolling backgrounds) from
//! static elements (HUDs, menus).

#[cfg(feature = "nova")]
use crate::bmp::encode_bmp;
#[cfg(feature = "nova")]
use crate::constants::{FRAME_HEIGHT, FRAME_RGBA_BYTES, FRAME_WIDTH};

/// A motion detector that processes frames and generates a heatmap of moving pixels.
#[cfg(feature = "nova")]
pub struct MotionDetector {
    previous_frame: std::vec::Vec<u8>,
    motion_heat: std::vec::Vec<f32>,
    decay_rate: f32,
    sensitivity: u8,
}

#[cfg(feature = "nova")]
impl Default for MotionDetector {
    fn default() -> Self {
        Self::new(0.9, 10)
    }
}

#[cfg(feature = "nova")]
impl MotionDetector {
    /// Creates a new `MotionDetector`.
    ///
    /// * `decay_rate` - How quickly the motion highlight fades (0.0 to 1.0).
    /// * `sensitivity` - Minimum color difference across RGB channels to be considered motion (0-255).
    #[must_use]
    pub fn new(decay_rate: f32, sensitivity: u8) -> Self {
        Self {
            previous_frame: vec![0; FRAME_RGBA_BYTES],
            motion_heat: vec![0.0; FRAME_WIDTH * FRAME_HEIGHT],
            decay_rate,
            sensitivity,
        }
    }

    /// Processes a new frame from the emulator, updating the motion heatmap.
    ///
    /// The input should be a standard 256x240 RGBA buffer.
    pub fn process_frame(&mut self, current_frame: &[u8]) {
        if current_frame.len() != FRAME_RGBA_BYTES {
            return;
        }

        for i in 0..(FRAME_WIDTH * FRAME_HEIGHT) {
            let offset = i * 4;

            let r_diff = (current_frame[offset] as i32 - self.previous_frame[offset] as i32).abs();
            let g_diff =
                (current_frame[offset + 1] as i32 - self.previous_frame[offset + 1] as i32).abs();
            let b_diff =
                (current_frame[offset + 2] as i32 - self.previous_frame[offset + 2] as i32).abs();

            let max_diff = r_diff.max(g_diff).max(b_diff) as u8;

            if max_diff >= self.sensitivity {
                self.motion_heat[i] = 1.0;
            } else {
                self.motion_heat[i] *= self.decay_rate;
                if self.motion_heat[i] < 0.01 {
                    self.motion_heat[i] = 0.0;
                }
            }
        }

        self.previous_frame.copy_from_slice(current_frame);
    }

    /// Renders the current motion heatmap as a 256x240 BMP image.
    ///
    /// Moving areas are highlighted in bright red, static areas are dark.
    pub fn render_bmp(&self) -> Result<std::vec::Vec<u8>, String> {
        let mut rgba = vec![0u8; FRAME_RGBA_BYTES];
        for i in 0..(FRAME_WIDTH * FRAME_HEIGHT) {
            let heat = self.motion_heat[i];
            let offset = i * 4;

            // Map heat (0.0 - 1.0) to red intensity
            let red = (heat * 255.0) as u8;

            rgba[offset] = red;
            rgba[offset + 1] = 0;
            rgba[offset + 2] = 0;
            rgba[offset + 3] = 255;
        }

        encode_bmp(FRAME_WIDTH, FRAME_HEIGHT, &rgba)
    }
}

#[cfg(all(test, feature = "nova"))]
mod tests {
    use super::*;

    #[test]
    fn should_detect_motion() {
        let mut detector = MotionDetector::new(0.5, 10);
        let frame1 = vec![0u8; FRAME_RGBA_BYTES];
        let mut frame2 = vec![0u8; FRAME_RGBA_BYTES];

        // Setup initial static frame
        detector.process_frame(&frame1);
        assert_eq!(detector.motion_heat[0], 0.0);

        // Modify pixel 0 in frame 2
        frame2[0] = 50; // R
        frame2[1] = 50; // G
        frame2[2] = 50; // B

        detector.process_frame(&frame2);
        assert_eq!(
            detector.motion_heat[0], 1.0,
            "Motion should be detected at pixel 0"
        );
        assert_eq!(detector.motion_heat[1], 0.0, "No motion at pixel 1");

        // Same frame again, motion should decay
        detector.process_frame(&frame2);
        assert_eq!(
            detector.motion_heat[0], 0.5,
            "Motion heat should decay to 0.5"
        );

        let bmp = detector.render_bmp().unwrap();
        assert_eq!(&bmp[0..2], b"BM", "Should render a valid BMP");
    }

    #[test]
    fn should_handle_wrong_frame_size() {
        let mut detector = MotionDetector::default();
        let bad_frame = vec![0u8; 10];
        detector.process_frame(&bad_frame); // Should simply return
    }
}
