//! Experimental audio oscilloscope visualizer.
//!
//! This module provides a way to render the raw audio samples generated by the APU
//! onto the RGBA framebuffer, creating a classic "oscilloscope" waveform overlay.
//! It bridges the audio domain (PCM samples) and the visual domain (pixels),
//! allowing players to "see" the music and sound effects.

#[cfg(feature = "nova")]
/// The visual style of the oscilloscope waveform.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OscilloscopeStyle {
    /// Renders a single pixel-thick line connecting the sample points.
    Line,
    /// Fills the area between the zero-crossing line and the sample points.
    Filled,
}

#[cfg(feature = "nova")]
/// A visualizer that renders an audio waveform onto an RGBA framebuffer.
pub struct OscilloscopeVisualizer {
    /// RGBA color to draw the waveform.
    pub color: [u8; 4],
    /// The style of the waveform.
    pub style: OscilloscopeStyle,
    /// A scaling factor to increase the amplitude of the visual waveform.
    pub amplitude_multiplier: f32,
}

#[cfg(feature = "nova")]
impl Default for OscilloscopeVisualizer {
    fn default() -> Self {
        Self {
            color: [0, 255, 0, 255], // Classic oscilloscope green
            style: OscilloscopeStyle::Line,
            amplitude_multiplier: 1.0,
        }
    }
}

#[cfg(feature = "nova")]
impl OscilloscopeVisualizer {
    /// Creates a new oscilloscope visualizer with default settings.
    pub fn new() -> Self {
        Self::default()
    }

    /// Renders an overlay of the provided audio samples onto the framebuffer.
    ///
    /// The `framebuffer` must be exactly `frame_width * frame_height * 4` bytes.
    /// The waveform is drawn in the lower half of the screen by default.
    ///
    /// ## Examples
    ///
    /// ```
    /// # use nes_core::experimental::oscilloscope::OscilloscopeVisualizer;
    /// let visualizer = OscilloscopeVisualizer::new();
    /// let mut fb = vec![0; 256 * 240 * 4];
    /// let samples = vec![100, -100, 50, -50];
    /// visualizer.render(&mut fb, 256, 240, &samples);
    /// ```
    pub fn render(
        &self,
        framebuffer: &mut [u8],
        frame_width: usize,
        frame_height: usize,
        samples: &[i16],
    ) {
        let expected_len = frame_width * frame_height * 4;
        if framebuffer.len() != expected_len || samples.is_empty() {
            return;
        }

        // We want to map the samples to the horizontal width of the screen.
        // If there are more samples than pixels, we will decimate (skip) samples.
        // If there are fewer samples than pixels, we will stretch them.
        let samples_per_pixel = (samples.len() as f32 / frame_width as f32).max(1.0);

        // Find the maximum absolute amplitude in the sample buffer to normalize the display
        let max_amp = samples
            .iter()
            .fold(1, |max, &val| max.max(val.abs() as i32)) as f32;

        // Define the drawing region (e.g., lower 1/4th of the screen)
        let draw_height = (frame_height / 4) as i32;
        let baseline_y = (frame_height - (draw_height as usize / 2)) as i32;

        let mut prev_y = baseline_y;

        for x in 0..frame_width {
            let sample_idx = ((x as f32) * samples_per_pixel) as usize;
            let sample_idx = sample_idx.min(samples.len() - 1);
            let sample = samples[sample_idx] as f32;

            // Normalize sample to [-1.0, 1.0] and scale to draw_height
            let normalized = if max_amp == 0.0 {
                0.0
            } else {
                (sample / max_amp) * self.amplitude_multiplier
            };
            let normalized = normalized.clamp(-1.0, 1.0);

            // Y grows downwards, so subtract the normalized amplitude
            let y = baseline_y - (normalized * (draw_height as f32 / 2.0)) as i32;
            let y = y.clamp(0, (frame_height - 1) as i32);

            match self.style {
                OscilloscopeStyle::Line => {
                    // Simple vertical line from prev_y to y to ensure continuous waveform
                    let y_start = y.min(prev_y);
                    let y_end = y.max(prev_y);
                    for draw_y in y_start..=y_end {
                        Self::draw_pixel(framebuffer, frame_width, x, draw_y as usize, self.color);
                    }
                }
                OscilloscopeStyle::Filled => {
                    // Fill from baseline to current y
                    let y_start = y.min(baseline_y);
                    let y_end = y.max(baseline_y);
                    for draw_y in y_start..=y_end {
                        Self::draw_pixel(framebuffer, frame_width, x, draw_y as usize, self.color);
                    }
                }
            }
            prev_y = y;
        }
    }

    #[inline(always)]
    fn draw_pixel(fb: &mut [u8], width: usize, x: usize, y: usize, color: [u8; 4]) {
        let idx = (y * width + x) * 4;
        // Optimization check bounds before assignment
        if idx + 3 < fb.len() {
            fb[idx] = color[0];
            fb[idx + 1] = color[1];
            fb[idx + 2] = color[2];
            // Don't overwrite alpha if we just want to blend, but we'll do solid replace here.
            fb[idx + 3] = color[3];
        }
    }
}

#[cfg(all(test, feature = "nova"))]
mod tests {
    use super::*;

    #[test]
    fn does_not_panic_on_invalid_framebuffer() {
        let visualizer = OscilloscopeVisualizer::new();
        let mut fb = vec![0; 10]; // Too small
        let samples = vec![100, -100];
        visualizer.render(&mut fb, 256, 240, &samples);
        // If we reach here, it didn't panic.
    }

    #[test]
    fn renders_line_waveform() {
        let visualizer = OscilloscopeVisualizer {
            color: [255, 0, 0, 255],
            style: OscilloscopeStyle::Line,
            amplitude_multiplier: 1.0,
        };
        let w = 4;
        let h = 4;
        let mut fb = vec![0; w * h * 4];
        let samples = vec![1000, 0, -1000, 0];

        visualizer.render(&mut fb, w, h, &samples);

        // Just verify some pixel got colored red
        let has_red = fb.chunks_exact(4).any(|pixel| pixel[0] == 255);
        assert!(has_red);
    }
}
