//! Experimental oscilloscope overlay for visualizing audio.
//!
//! This module takes the raw audio samples generated by the APU and draws
//! them directly onto the emulator's framebuffer as a glowing waveform.
//! This is a true "mashup" of the audio and video pipelines!

#[cfg(feature = "nova")]
use crate::constants::{FRAME_HEIGHT, FRAME_RGBA_BYTES, FRAME_WIDTH};

#[cfg(feature = "nova")]
/// Overlays an oscilloscope waveform of the APU audio onto a framebuffer.
pub struct OscilloscopeOverlay;

#[cfg(feature = "nova")]
impl OscilloscopeOverlay {
    /// Draws the given audio samples as a waveform on the framebuffer.
    ///
    /// The `framebuffer` must be `FRAME_WIDTH * FRAME_HEIGHT * 4` bytes (RGBA).
    /// The `samples` are expected to be 16-bit PCM audio.
    ///
    /// ## Examples
    ///
    /// ```
    /// # use nes_core::experimental::oscilloscope_overlay::OscilloscopeOverlay;
    /// # use nes_core::constants::FRAME_RGBA_BYTES;
    /// let mut framebuffer = vec![0; FRAME_RGBA_BYTES];
    /// let samples = vec![0, 16384, 32767, -16384, -32768];
    /// OscilloscopeOverlay::apply(&mut framebuffer, &samples);
    /// ```
    pub fn apply(framebuffer: &mut [u8], samples: &[i16]) {
        if samples.is_empty() || framebuffer.len() != FRAME_RGBA_BYTES {
            return;
        }

        let mid_y = (FRAME_HEIGHT / 2) as isize;
        let scale = (FRAME_HEIGHT / 4) as f32 / 32768.0;

        let mut prev_y = mid_y - (samples[0] as f32 * scale) as isize;

        for (i, &sample) in samples.iter().enumerate() {
            let x = (i * FRAME_WIDTH) / samples.len();
            if x >= FRAME_WIDTH {
                break;
            }

            let y_offset = (sample as f32 * scale) as isize;
            let y = mid_y - y_offset;

            // Draw simple vertical lines to connect the waveform
            let y_start = prev_y.min(y);
            let y_end = prev_y.max(y);

            for draw_y in y_start..=y_end {
                if draw_y >= 0 && draw_y < FRAME_HEIGHT as isize {
                    let idx = ((draw_y as usize) * FRAME_WIDTH + x) * 4;
                    framebuffer[idx] = 50;
                    framebuffer[idx + 1] = 255;
                    framebuffer[idx + 2] = 50;
                    framebuffer[idx + 3] = 255;
                }
            }

            prev_y = y;
        }
    }
}

#[cfg(all(test, feature = "nova"))]
mod tests {
    use super::*;
    use crate::constants::{FRAME_HEIGHT, FRAME_RGBA_BYTES, FRAME_WIDTH};

    #[test]
    fn test_oscilloscope_overlay() {
        let mut framebuffer = vec![0; FRAME_RGBA_BYTES];
        let samples = vec![0, 32767, -32768];

        OscilloscopeOverlay::apply(&mut framebuffer, &samples);

        // Midpoint should be green (sample 0)
        let mid_idx = ((FRAME_HEIGHT / 2) * FRAME_WIDTH) * 4;
        assert_eq!(framebuffer[mid_idx + 1], 255);
    }
}
