[package]
name = "nes-test-harness"
version = "0.1.0"
edition = "2024"

[dependencies]
nes-core = { path = "../nes-core" }
nes-config = { path = "../nes-config" }
nes-netplay = { path = "../nes-netplay" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
nes-dsl = { version = "0.1.0", path = "../nes-dsl" }

[dev-dependencies]
