use crate::AddressingMode;

pub(crate) fn opcode_for(mnemonic: &str, mode: AddressingMode) -> Option<u8> {
    use AddressingMode::{
        Absolute, AbsoluteX, AbsoluteY, Accumulator, Immediate, Implied, Indirect, IndirectX,
        IndirectY, Relative, ZeroPage, ZeroPageX, ZeroPageY,
    };

    Some(match (mnemonic, mode) {
        ("ADC", Immediate) => 0x69,
        ("ADC", ZeroPage) => 0x65,
        ("ADC", ZeroPageX) => 0x75,
        ("ADC", Absolute) => 0x6D,
        ("ADC", AbsoluteX) => 0x7D,
        ("ADC", AbsoluteY) => 0x79,
        ("ADC", IndirectX) => 0x61,
        ("ADC", IndirectY) => 0x71,

        ("AND", Immediate) => 0x29,
        ("AND", ZeroPage) => 0x25,
        ("AND", ZeroPageX) => 0x35,
        ("AND", Absolute) => 0x2D,
        ("AND", AbsoluteX) => 0x3D,
        ("AND", AbsoluteY) => 0x39,
        ("AND", IndirectX) => 0x21,
        ("AND", IndirectY) => 0x31,

        ("ASL", Accumulator) => 0x0A,
        ("ASL", ZeroPage) => 0x06,
        ("ASL", ZeroPageX) => 0x16,
        ("ASL", Absolute) => 0x0E,
        ("ASL", AbsoluteX) => 0x1E,

        ("BCC", Relative) => 0x90,
        ("BCS", Relative) => 0xB0,
        ("BEQ", Relative) => 0xF0,
        ("BIT", ZeroPage) => 0x24,
        ("BIT", Absolute) => 0x2C,
        ("BMI", Relative) => 0x30,
        ("BNE", Relative) => 0xD0,
        ("BPL", Relative) => 0x10,
        ("BRK", Implied) => 0x00,
        ("BVC", Relative) => 0x50,
        ("BVS", Relative) => 0x70,

        ("CLC", Implied) => 0x18,
        ("CLD", Implied) => 0xD8,
        ("CLI", Implied) => 0x58,
        ("CLV", Implied) => 0xB8,

        ("CMP", Immediate) => 0xC9,
        ("CMP", ZeroPage) => 0xC5,
        ("CMP", ZeroPageX) => 0xD5,
        ("CMP", Absolute) => 0xCD,
        ("CMP", AbsoluteX) => 0xDD,
        ("CMP", AbsoluteY) => 0xD9,
        ("CMP", IndirectX) => 0xC1,
        ("CMP", IndirectY) => 0xD1,

        ("CPX", Immediate) => 0xE0,
        ("CPX", ZeroPage) => 0xE4,
        ("CPX", Absolute) => 0xEC,
        ("CPY", Immediate) => 0xC0,
        ("CPY", ZeroPage) => 0xC4,
        ("CPY", Absolute) => 0xCC,

        ("DEC", ZeroPage) => 0xC6,
        ("DEC", ZeroPageX) => 0xD6,
        ("DEC", Absolute) => 0xCE,
        ("DEC", AbsoluteX) => 0xDE,
        ("DEX", Implied) => 0xCA,
        ("DEY", Implied) => 0x88,

        ("EOR", Immediate) => 0x49,
        ("EOR", ZeroPage) => 0x45,
        ("EOR", ZeroPageX) => 0x55,
        ("EOR", Absolute) => 0x4D,
        ("EOR", AbsoluteX) => 0x5D,
        ("EOR", AbsoluteY) => 0x59,
        ("EOR", IndirectX) => 0x41,
        ("EOR", IndirectY) => 0x51,

        ("INC", ZeroPage) => 0xE6,
        ("INC", ZeroPageX) => 0xF6,
        ("INC", Absolute) => 0xEE,
        ("INC", AbsoluteX) => 0xFE,
        ("INX", Implied) => 0xE8,
        ("INY", Implied) => 0xC8,

        ("JMP", Absolute) => 0x4C,
        ("JMP", Indirect) => 0x6C,
        ("JSR", Absolute) => 0x20,

        ("LDA", Immediate) => 0xA9,
        ("LDA", ZeroPage) => 0xA5,
        ("LDA", ZeroPageX) => 0xB5,
        ("LDA", Absolute) => 0xAD,
        ("LDA", AbsoluteX) => 0xBD,
        ("LDA", AbsoluteY) => 0xB9,
        ("LDA", IndirectX) => 0xA1,
        ("LDA", IndirectY) => 0xB1,

        ("LDX", Immediate) => 0xA2,
        ("LDX", ZeroPage) => 0xA6,
        ("LDX", ZeroPageY) => 0xB6,
        ("LDX", Absolute) => 0xAE,
        ("LDX", AbsoluteY) => 0xBE,

        ("LDY", Immediate) => 0xA0,
        ("LDY", ZeroPage) => 0xA4,
        ("LDY", ZeroPageX) => 0xB4,
        ("LDY", Absolute) => 0xAC,
        ("LDY", AbsoluteX) => 0xBC,

        ("LSR", Accumulator) => 0x4A,
        ("LSR", ZeroPage) => 0x46,
        ("LSR", ZeroPageX) => 0x56,
        ("LSR", Absolute) => 0x4E,
        ("LSR", AbsoluteX) => 0x5E,

        ("NOP", Implied) => 0xEA,

        ("ORA", Immediate) => 0x09,
        ("ORA", ZeroPage) => 0x05,
        ("ORA", ZeroPageX) => 0x15,
        ("ORA", Absolute) => 0x0D,
        ("ORA", AbsoluteX) => 0x1D,
        ("ORA", AbsoluteY) => 0x19,
        ("ORA", IndirectX) => 0x01,
        ("ORA", IndirectY) => 0x11,

        ("PHA", Implied) => 0x48,
        ("PHP", Implied) => 0x08,
        ("PLA", Implied) => 0x68,
        ("PLP", Implied) => 0x28,

        ("ROL", Accumulator) => 0x2A,
        ("ROL", ZeroPage) => 0x26,
        ("ROL", ZeroPageX) => 0x36,
        ("ROL", Absolute) => 0x2E,
        ("ROL", AbsoluteX) => 0x3E,

        ("ROR", Accumulator) => 0x6A,
        ("ROR", ZeroPage) => 0x66,
        ("ROR", ZeroPageX) => 0x76,
        ("ROR", Absolute) => 0x6E,
        ("ROR", AbsoluteX) => 0x7E,

        ("RTI", Implied) => 0x40,
        ("RTS", Implied) => 0x60,

        ("SBC", Immediate) => 0xE9,
        ("SBC", ZeroPage) => 0xE5,
        ("SBC", ZeroPageX) => 0xF5,
        ("SBC", Absolute) => 0xED,
        ("SBC", AbsoluteX) => 0xFD,
        ("SBC", AbsoluteY) => 0xF9,
        ("SBC", IndirectX) => 0xE1,
        ("SBC", IndirectY) => 0xF1,

        ("SEC", Implied) => 0x38,
        ("SED", Implied) => 0xF8,
        ("SEI", Implied) => 0x78,

        ("STA", ZeroPage) => 0x85,
        ("STA", ZeroPageX) => 0x95,
        ("STA", Absolute) => 0x8D,
        ("STA", AbsoluteX) => 0x9D,
        ("STA", AbsoluteY) => 0x99,
        ("STA", IndirectX) => 0x81,
        ("STA", IndirectY) => 0x91,

        ("STX", ZeroPage) => 0x86,
        ("STX", ZeroPageY) => 0x96,
        ("STX", Absolute) => 0x8E,

        ("STY", ZeroPage) => 0x84,
        ("STY", ZeroPageX) => 0x94,
        ("STY", Absolute) => 0x8C,

        ("TAX", Implied) => 0xAA,
        ("TAY", Implied) => 0xA8,
        ("TSX", Implied) => 0xBA,
        ("TXA", Implied) => 0x8A,
        ("TXS", Implied) => 0x9A,
        ("TYA", Implied) => 0x98,
        _ => return None,
    })
}
