//! Hardware audio abstraction and playback pipeline.
//!
//! This module acts as the bridge between the raw audio samples generated by `nes-core`
//! and the host operating system's audio hardware. It handles queuing, buffering, and
//! backpressure to ensure smooth audio playback without stuttering or overwhelming the
//! audio device.
//!
//! The core of the module is the [`crate::audio::AudioOutput`] struct, which manages the audio stream
//! and sink. It uses a trait-based approach ([`crate::audio::AudioSinkControl`]) to allow decoupling
//! the underlying audio library (`rodio`) for testing purposes.

use nes_core::AUDIO_SAMPLE_RATE;
use rodio::buffer::SamplesBuffer;
use rodio::{OutputStream, Sink};

/// The maximum number of audio chunks that can be queued before applying backpressure.
///
/// If the queue is full, further audio samples will be dropped to maintain low latency.
pub const MAX_AUDIO_QUEUE_CHUNKS: usize = 8;

/// The number of audio channels used by the NES (mono output).
pub const AUDIO_CHANNELS: u16 = 1;

/// Defines the required operations for interacting with an audio sink.
///
/// This trait exists primarily to decouple the `nes-desktop` audio pipeline
/// from the underlying `rodio::Sink` implementation. By defining a trait,
/// we can mock the audio sink in tests (e.g., `FakeAudioSink`), ensuring
/// the queue logic and backpressure can be tested without needing actual
/// audio hardware or generating noise during test runs.
pub trait AudioSinkControl {
    /// Returns the number of unplayed audio chunks currently queued.
    fn queue_len(&self) -> usize;

    /// Appends a new chunk of 16-bit PCM samples to the playback queue.
    fn append_i16(&self, samples: Vec<i16>);

    /// Clears all queued audio chunks.
    fn clear(&self);

    /// Stops playback and mutes the output.
    fn stop(&self);
}

/// A concrete implementation of [`crate::audio::AudioSinkControl`] that wraps a `rodio::Sink`.
///
/// This struct adapts the standard `rodio` sink interface into our application's
/// required trait, allowing it to be used dynamically via dynamic dispatch (`Box<dyn AudioSinkControl>`).
pub struct RodioSinkAdapter {
    inner: Sink,
}

impl AudioSinkControl for RodioSinkAdapter {
    fn queue_len(&self) -> usize {
        self.inner.len()
    }

    fn append_i16(&self, samples: Vec<i16>) {
        self.inner.append(SamplesBuffer::new(
            AUDIO_CHANNELS,
            AUDIO_SAMPLE_RATE,
            samples,
        ));
    }

    fn clear(&self) {
        self.inner.clear();
    }

    fn stop(&self) {
        self.inner.stop();
    }
}

/// Manages the playback of NES audio samples to the host system's audio device.
///
/// `AudioOutput` queues PCM chunks generated by the emulator core. To prevent memory
/// exhaustion and maintain low latency between the emulator state and heard audio,
/// it limits the queue to [`MAX_AUDIO_QUEUE_CHUNKS`]. When the queue is full,
/// backpressure is applied and further samples are dropped until space frees up.
pub struct AudioOutput {
    sink: Box<dyn AudioSinkControl>,
    _stream: Option<OutputStream>,
}

impl AudioOutput {
    /// Creates a new `AudioOutput` with a provided sink and an optional stream.
    ///
    /// This is primarily used for dependency injection during testing (e.g., passing a
    /// mock sink). For normal usage, prefer [`try_new`](Self::try_new).
    pub fn new_with_sink(sink: Box<dyn AudioSinkControl>, stream: Option<OutputStream>) -> Self {
        Self {
            sink,
            _stream: stream,
        }
    }

    /// Attempts to initialize the host OS audio output.
    ///
    /// ## Errors
    /// Returns an error message if the default audio output device cannot be found
    /// or if the `rodio` sink fails to initialize (e.g., if the host environment
    /// has no audio hardware or permissions).
    pub fn try_new() -> Result<Self, String> {
        let (stream, handle) = OutputStream::try_default()
            .map_err(|err| format!("Audio output init failed: {err}"))?;
        let sink =
            Sink::try_new(&handle).map_err(|err| format!("Audio sink init failed: {err}"))?;
        let sink_adapter = RodioSinkAdapter { inner: sink };
        Ok(Self::new_with_sink(Box::new(sink_adapter), Some(stream)))
    }

    /// Queues a chunk of PCM audio samples for playback.
    ///
    /// If the internal sink queue has reached [`MAX_AUDIO_QUEUE_CHUNKS`], backpressure
    /// occurs: the incoming `samples` are immediately discarded and `false` is returned.
    /// This prevents unbounded memory growth and keeps the audio latency tight.
    ///
    /// ## Examples
    /// ```rust
    /// use nes_desktop::audio::{AudioOutput, AudioSinkControl};
    ///
    /// struct DummySink;
    /// impl AudioSinkControl for DummySink {
    ///     fn queue_len(&self) -> usize { 0 }
    ///     fn append_i16(&self, _samples: Vec<i16>) {}
    ///     fn clear(&self) {}
    ///     fn stop(&self) {}
    /// }
    ///
    /// let audio = AudioOutput::new_with_sink(Box::new(DummySink), None);
    ///
    /// // Queuing samples succeeds as the queue is empty
    /// let samples = vec![0_i16; 100];
    /// assert!(audio.queue_samples(samples));
    /// ```
    pub fn queue_samples(&self, samples: Vec<i16>) -> bool {
        if self.sink.queue_len() >= MAX_AUDIO_QUEUE_CHUNKS {
            return false;
        }
        self.sink.append_i16(samples);
        true
    }

    /// Returns the number of unplayed audio chunks currently queued.
    ///
    /// The maximum length is determined by [`MAX_AUDIO_QUEUE_CHUNKS`].
    pub fn queue_len(&self) -> usize {
        self.sink.queue_len()
    }

    /// Abruptly clears the entire playback queue.
    ///
    /// The audio device will stop playing the current buffer and silence will follow until
    /// more samples are queued. This is useful for stopping output instantly or resynchronizing
    /// the emulator with the audio stream.
    pub fn clear(&self) {
        self.sink.clear();
    }
}

impl Drop for AudioOutput {
    fn drop(&mut self) {
        // Ensure sink teardown happens while the stream backend is still alive.
        self.sink.stop();
    }
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use std::sync::{Arc, Mutex};

    #[derive(Default)]
    pub struct FakeAudioState {
        pub queue_len: usize,
        pub append_calls: usize,
        pub appended_sample_count: usize,
        pub clear_calls: usize,
        pub stop_calls: usize,
    }

    /// A mock implementation of [`crate::audio::AudioSinkControl`] for unit testing without audio hardware.
    ///
    /// The `FakeAudioSink` captures all interactions (queueing samples, clearing, stopping)
    /// into a shared `FakeAudioState`. This allows tests to assert that the `AudioOutput`
    /// correctly forwards commands or applies backpressure without needing a real `rodio::Sink`.
    pub struct FakeAudioSink {
        pub state: Arc<Mutex<FakeAudioState>>,
    }

    impl FakeAudioSink {
        /// Creates a new `FakeAudioSink` with a starting queue length and returns
        /// a shared handle to its state.
        ///
        /// The `initial_len` parameter is typically used to simulate a full queue
        /// to test backpressure logic.
        pub fn with_len(initial_len: usize) -> (Self, Arc<Mutex<FakeAudioState>>) {
            let state = Arc::new(Mutex::new(FakeAudioState {
                queue_len: initial_len,
                ..Default::default()
            }));
            (
                Self {
                    state: Arc::clone(&state),
                },
                state,
            )
        }
    }

    impl AudioSinkControl for FakeAudioSink {
        fn queue_len(&self) -> usize {
            self.state
                .lock()
                .expect("fake audio state lock should not poison")
                .queue_len
        }

        fn append_i16(&self, samples: Vec<i16>) {
            let mut state = self
                .state
                .lock()
                .expect("fake audio state lock should not poison");
            state.append_calls = state.append_calls.saturating_add(1);
            state.appended_sample_count = state.appended_sample_count.saturating_add(samples.len());
            state.queue_len = state.queue_len.saturating_add(1);
        }

        fn stop(&self) {
            let mut state = self
                .state
                .lock()
                .expect("fake audio state lock should not poison");
            state.stop_calls = state.stop_calls.saturating_add(1);
        }

        fn clear(&self) {
            let mut state = self
                .state
                .lock()
                .expect("fake audio state lock should not poison");
            state.clear_calls = state.clear_calls.saturating_add(1);
            state.queue_len = 0;
        }
    }

    #[test]
    fn audio_output_queue_and_drop_behave_with_fake_sink() {
        let (fake_sink, shared_state) = FakeAudioSink::with_len(MAX_AUDIO_QUEUE_CHUNKS - 1);
        let output = AudioOutput::new_with_sink(Box::new(fake_sink), None);

        assert!(output.queue_samples(vec![1_i16, 2, 3]));
        assert_eq!(output.queue_len(), MAX_AUDIO_QUEUE_CHUNKS);

        let state_after_queue = shared_state
            .lock()
            .expect("fake audio state lock should not poison");
        assert_eq!(state_after_queue.append_calls, 1);
        assert_eq!(state_after_queue.appended_sample_count, 3);
        drop(state_after_queue);

        drop(output);
        let state_after_drop = shared_state
            .lock()
            .expect("fake audio state lock should not poison");
        assert_eq!(state_after_drop.stop_calls, 1);
    }

    #[test]
    fn audio_output_rejects_samples_when_queue_is_full() {
        let (fake_sink, shared_state) = FakeAudioSink::with_len(MAX_AUDIO_QUEUE_CHUNKS);
        let output = AudioOutput::new_with_sink(Box::new(fake_sink), None);

        assert!(!output.queue_samples(vec![1_i16, 2, 3]));
        assert_eq!(output.queue_len(), MAX_AUDIO_QUEUE_CHUNKS);

        let state = shared_state
            .lock()
            .expect("fake audio state lock should not poison");
        assert_eq!(state.append_calls, 0);
    }

    #[test]
    fn audio_output_clear_forwards_to_sink_and_empties_queue() {
        let (fake_sink, shared_state) = FakeAudioSink::with_len(3);
        let output = AudioOutput::new_with_sink(Box::new(fake_sink), None);

        output.clear();

        let state = shared_state
            .lock()
            .expect("fake audio state lock should not poison");
        assert_eq!(state.clear_calls, 1);
        assert_eq!(state.queue_len, 0);
    }

    #[test]
    fn rodio_sink_adapter_forwards_append_and_queue_len() {
        let (sink, _queue_rx) = Sink::new_idle();
        let adapter = RodioSinkAdapter { inner: sink };

        assert_eq!(adapter.queue_len(), 0);
        adapter.append_i16(vec![1_i16, 2, 3, 4]);
        assert_eq!(adapter.queue_len(), 1);
        adapter.append_i16(vec![5_i16, 6, 7, 8]);
        assert_eq!(adapter.queue_len(), 2);
    }

    #[test]
    fn rodio_sink_adapter_stop_mutes_idle_queue_output() {
        let (sink, mut queue_rx) = Sink::new_idle();
        let adapter = RodioSinkAdapter { inner: sink };

        adapter.append_i16(vec![i16::MAX; 5_000]);
        assert_eq!(
            queue_rx.next(),
            Some(0.999_969_5),
            "i16::MAX should map to a non-zero sample before stop"
        );

        adapter.stop();

        let saw_silence = (0..600).any(|_| queue_rx.next() == Some(0.0));
        assert!(saw_silence, "stop should silence the queued source");
    }
}
